import {
  Apple, ArrowLeftRight, Baby, Banknote, Beer, Bike, BookOpen, Briefcase, Brush, Building2, Bus, Camera, Car, Cat,
  Church, CirclePlus, Cloud, Code, Coffee, Coins, CreditCard, Dog, Droplet, Dumbbell, Film, Flame, Fuel, Gamepad2,
  Gem, Gift, Glasses, Globe, GraduationCap, Hammer, HandCoins, HandHeart, Headphones, Heart, HeartHandshake,
  HeartPulse, Hotel, House, Landmark, Laptop, Leaf, Lightbulb, MapPin, Monitor, Music, Package, Palette, PiggyBank,
  Pill, Pizza, Plane, Popcorn, Receipt, Repeat, Sandwich, School, Scissors, Shield, Shirt, ShoppingBag, ShoppingCart,
  Smartphone, Sparkles, Star, Stethoscope, Sun, Tag, Target, Ticket, Train, TrendingUp, Trophy, Truck, Tv, Umbrella,
  User, Users, Utensils, Wallet, Wifi, Wine, Wrench, Zap,
} from 'lucide-react'

// Icon keys are stored in the database (kebab-case)
export const CATEGORY_ICONS = {
  'shopping-cart': ShoppingCart,
  house: House,
  bus: Bus,
  receipt: Receipt,
  wifi: Wifi,
  'heart-pulse': HeartPulse,
  shield: Shield,
  utensils: Utensils,
  coffee: Coffee,
  ticket: Ticket,
  'shopping-bag': ShoppingBag,
  repeat: Repeat,
  'gamepad-2': Gamepad2,
  smartphone: Smartphone,
  plane: Plane,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  code: Code,
  school: School,
  dumbbell: Dumbbell,
  church: Church,
  'hand-heart': HandHeart,
  'heart-handshake': HeartHandshake,
  gift: Gift,
  'credit-card': CreditCard,
  briefcase: Briefcase,
  laptop: Laptop,
  'circle-plus': CirclePlus,
  'piggy-bank': PiggyBank,
  'trending-up': TrendingUp,
  'arrow-left-right': ArrowLeftRight,
  'hand-coins': HandCoins,
  car: Car,
  fuel: Fuel,
  train: Train,
  bike: Bike,
  truck: Truck,
  pizza: Pizza,
  sandwich: Sandwich,
  apple: Apple,
  beer: Beer,
  wine: Wine,
  popcorn: Popcorn,
  film: Film,
  tv: Tv,
  music: Music,
  headphones: Headphones,
  camera: Camera,
  palette: Palette,
  brush: Brush,
  shirt: Shirt,
  scissors: Scissors,
  gem: Gem,
  glasses: Glasses,
  pill: Pill,
  stethoscope: Stethoscope,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  users: Users,
  user: User,
  heart: Heart,
  hotel: Hotel,
  'map-pin': MapPin,
  umbrella: Umbrella,
  sun: Sun,
  globe: Globe,
  cloud: Cloud,
  monitor: Monitor,
  lightbulb: Lightbulb,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  wrench: Wrench,
  hammer: Hammer,
  'building-2': Building2,
  landmark: Landmark,
  banknote: Banknote,
  coins: Coins,
  wallet: Wallet,
  package: Package,
  leaf: Leaf,
  trophy: Trophy,
  target: Target,
  star: Star,
  sparkles: Sparkles,
  tag: Tag,
}

export const ICON_KEYS = Object.keys(CATEGORY_ICONS)

export function getCategoryIcon(key) {
  return CATEGORY_ICONS[key] ?? Tag
}
